# Generated by Django 4.1.5 on 2023-01-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='start',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='ride',
            name='arriv_time',
            field=models.TimeField(),
        ),
    ]
